name: Docker CI Learning - KUCL 
on:
  push:
jobs:
  docker_1:
    runs-on: ubuntu-latest 
      #labels: kucl22 
         
    steps:
      -
        name: Set up QEMU test
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/kucl2:actions
  deploy:
    needs: docker_1
    name: k8s deployment
    runs-on: ubuntu-latest  # You might want to use an appropriate label like 'kucl2' here if required
    steps:
      - name: Set up kubeconfig
        run: |
          mkdir -p ${HOME}/.kube
          echo ${{ secrets.MYKUBECONFIG }} | base64 --decode > ${HOME}/.kube/config
      - name: Create Kubernetes Deployment
        run: kubectl create deployment githubaction --image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/kucl2:actions
